/**
 * Generated by orval 🍺
 * Do not edit manually.
 * AppStart API
 * API REST do AppStart - Especificação OpenAPI 3.0
 * OpenAPI spec version: 1.0.0
 */

export interface TeamDto {
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  ownerId: string;
  createdAt: string;
  updatedAt: string;
}
